version: "3"

tasks:
  default:
    desc: Run the price checker with database and card list (Default Behavior)
    cmds:
      - python3 mtg_price_checker.py --database sqlite check --list cards.json

  typecheck:
    desc: Run strict type checking
    cmds:
      - mypy mtg_price_checker.py --strict

  lint:
    desc: Run linter
    cmds:
      - pylint mtg_price_checker.py
